name: Called workflow

on:
  workflow_call:
    inputs:
      name:
      description: app name
      required: true
      type: string
    secrets:
      SUBSCRIPTION_ID:
        description: subscription id
        required: true
      BACKEND_CONFIG:
        description: backend config
        required: true
      
   
