name: Called workflow

on:
  workflow_call:
    inputs:
      name:
        description: app name
        required: true
        type: string
      subscription_id:
        description: sub id
        required: true
        type: string
      backend_config:
        description: backend config
        required: true
        type: string        
jobs:
  plan:
    name: TF Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Debug
        id: debug
        run: |
          set -x
          # echo "${{ secrets.SUBSCRIPTION_ID }}" | sed 's/./& /g' 
          # echo "${{ secrets.BACKEND_CONFIG }}" | sed 's/./& /g' 
          echo "sub_id: ${{ vars.SUBSCRIPTION_ID }}" 
          echo "backend_config: ${{ vars.BACKEND_CONFIG }}"         
          
      
   
