name: Called workflow

on:
  workflow_call:
    inputs:
      name:
        description: app name
        required: true
        type: string
    secrets:
      SUBSCRIPTION_ID:
        description: subscription id
        required: true
      BACKEND_CONFIG:
        description: backend config
        required: true
jobs:
  plan:
    name: TF Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Debug
        id: debug
        run: |
          set -x
          echo " sub id: ${{ secrets.SUBSCRIPTION_ID }}" | sed 's/./& /g' 
          echo " backend_config: ${{ secrets.BACKEND_CONFIG }}" | sed 's/./& /g' 
          
      
   
